apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: devops-toolkit
spec:
  components:
  - name: backend
    type: backend
    properties:
      image: vfarcic/backend
  - name: frontend
    type: frontend
    properties:
      name: frontend
      image: vfarcic/devops-toolkit-series
    traits:
    - type: autoscaler
      properties:
        min: 3
    - type: ingress
      properties:
        domain: localhost
        http:
          "/": 80