apiVersion: devopstoolkitseries.com/v1alpha1
kind: CompositeCluster
metadata:
  name: a-team
spec:
  id: a-team
  compositionRef:
    name: cluster-aws
  parameters:
    nodeSize: small
    minNodeCount: 3
